version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - TZ=America/Chicago
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  server:
    build: ./server
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql
      - MYSQLUSER=root
      - MYSQLPASS=example
      - TZ=America/Chicago

    volumes:
      - ./server/backend:/app/backend
      - /usr/scr/app/node_modules
      - ./server/frontend:/app/frontend
    ports:
      - "8000:80"
